AllCops:
  NewCops: enable
  Exclude:
    - "*/schema.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
